### ISSUE TITLE
Feature Wish: Configurable Text next to Icons (currently GitHub)

### ISSUE THREAD

**Issue by christophhillisch** [ojacques/mkdocs-git-committers-plugin-2#45]
Hi,

I would like to configure what is written next to the icons of the contributors. I believe it would be nice to spell out Contributors instead of GitHub, because the GitHub logo is already on the side, but what is not clear to readers is that these people are listed, because they contributed to this article. It therefore would be really great if we could configure the text between the GitHub icon and the contributors. 

Thanks!

**Comment by ojacques** [comment]
Thanks @christophhillisch - it is a great idea. I am guessing you are using this plugin in the context of mkdocs-material theme. In which case, this feature will have to be requested for mkdocs-material, [here](https://github.com/squidfunk/mkdocs-material/issues), and probably [discussed before](https://github.com/squidfunk/mkdocs-material/discussions).

Hint: the code to change is on those 2 lines: 
https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/source-file.html#L78 and https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/source-file.html#L86

I will close this issue, as this seems to be outside of what this plugin does. Let me know otherwise!
